/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import model.Jugada;

/**
 *
 * @author JEFFREY
 */
public class CrearPDF extends javax.swing.JFrame {
    /**
     * Creates new form CrearPDF
     */
    public CrearPDF() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../resources/icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        a1 = new javax.swing.JComboBox(application.EntrenadorDeAjedrez.getPartida().getListaDeJugadas().toArray());
        a2 = new javax.swing.JComboBox(application.EntrenadorDeAjedrez.getPartida().getListaDeJugadas().toArray());
        c2 = new javax.swing.JComboBox(application.EntrenadorDeAjedrez.getPartida().getListaDeJugadas().toArray());
        b2 = new javax.swing.JComboBox(application.EntrenadorDeAjedrez.getPartida().getListaDeJugadas().toArray());
        c1 = new javax.swing.JComboBox(application.EntrenadorDeAjedrez.getPartida().getListaDeJugadas().toArray());
        b1 = new javax.swing.JComboBox(application.EntrenadorDeAjedrez.getPartida().getListaDeJugadas().toArray());
        base = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entrenador de Ajedrez");
        setMaximumSize(new java.awt.Dimension(400, 700));
        setMinimumSize(new java.awt.Dimension(400, 700));
        setPreferredSize(new java.awt.Dimension(400, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Crear PDF");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 380, -1));

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, -1, -1));

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        getContentPane().add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 640, -1, -1));

        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 120, -1));

        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 120, -1));

        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 120, -1));

        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 120, -1));

        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 120, -1));

        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 120, -1));

        base.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/base2.png"))); // NOI18N
        getContentPane().add(base, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 61, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a2ActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        Date date = new Date() ;
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH-mm-ss");
        ArrayList<Jugada> jugadasPDF = new ArrayList<>();
        jugadasPDF.add( (Jugada) a1.getSelectedItem());
        jugadasPDF.add( (Jugada) a2.getSelectedItem());
        jugadasPDF.add( (Jugada) b1.getSelectedItem());
        jugadasPDF.add( (Jugada) b2.getSelectedItem());
        jugadasPDF.add( (Jugada) c1.getSelectedItem());
        jugadasPDF.add( (Jugada) c2.getSelectedItem());
        ArrayList<BufferedImage> input = new ArrayList<>();
        BufferedImage boardSprite = null;
        try {
            boardSprite = ImageIO.read(new File("src/resources/base.png"));
        } catch (IOException ex) {
            Logger.getLogger(CrearPDF.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            for (int i = 0; i < jugadasPDF.size(); i++) {
                input.add(ImageIO.read(jugadasPDF.get(i).getImagen()));
            }
        } catch (IOException ex) {
            Logger.getLogger(CrearJugadaTactica.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedImage output = new BufferedImage( 
        boardSprite.getWidth(), 
        boardSprite.getHeight(), 
        BufferedImage.TYPE_INT_ARGB ); 
        Graphics g = output.getGraphics();
        g.drawImage(boardSprite, 0, 0, null );
        g.drawImage(input.get(0), 30, 30, 810, 810, null );
        g.drawImage(input.get(1), 850, 30, 810, 810, null );
        g.drawImage(input.get(2), 30, 850, 810, 810, null );
        g.drawImage(input.get(3), 850, 850, 810, 810, null );
        g.drawImage(input.get(4), 30, 1670, 810, 810, null );
        g.drawImage(input.get(5), 850, 1670, 810, 810, null );
        File p = new File( (System.getProperty("user.home") + 
                System.getProperty("file.separator") +  
                System.getProperty("file.separator") + dateFormat.format(date) + ".png"));
        try {
            ImageIO.write( output, "PNG", p );
        } catch (IOException ex) {
            Logger.getLogger(CrearJugadaTactica.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_guardarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox a1;
    private javax.swing.JComboBox a2;
    private javax.swing.JComboBox b1;
    private javax.swing.JComboBox b2;
    private javax.swing.JLabel base;
    private javax.swing.JComboBox c1;
    private javax.swing.JComboBox c2;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
