/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.nio.channels.FileChannel;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Jugada;
import model.JugadaTactica;
import model.Partida;

/**
 *
 * @author jeffrey-lmde
 */
public class EditarJugadaTactica extends javax.swing.JFrame {
    private File fichero;
    private int index;
    private JugadaTactica jugada;
    private Partida partida;
    
    /**
     * Creates new form CrearJugadaTeorica
     */
    public EditarJugadaTactica(int pIndex) {
        initComponents();
        partida = application.EntrenadorDeAjedrez.getPartida();
        index = pIndex;
        jugada = (JugadaTactica) partida.getListaDeJugadas().get(index);
        fichero = jugada.getImagen();
        jugadorBlancoTXT.setText(jugada.getJugadorBlanco());
        jugadorNegroTXT.setText(jugada.getJugadorNegro());
        anioTXT.setText(jugada.getAnio());
        setBoardPicture();
        setIconImage(new ImageIcon(getClass().getResource("../resources/icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jugadorBlanco = new javax.swing.JLabel();
        guardar = new javax.swing.JToggleButton();
        jugadorBlancoTXT = new javax.swing.JTextField();
        jugadorNegroTXT = new javax.swing.JTextField();
        jugadorNegro = new javax.swing.JLabel();
        anioTXT = new javax.swing.JTextField();
        anio = new javax.swing.JLabel();
        cargarFoto = new javax.swing.JButton();
        direccionImagen = new javax.swing.JLabel();
        tablero = new javax.swing.JLabel();
        cancelar1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entrenador de Ajedrez");
        setMinimumSize(new java.awt.Dimension(500, 680));
        setResizable(false);

        titulo.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Jugada Tactica");

        jugadorBlanco.setText("Jugador blanco:");

        guardar.setText("Guardar");
        guardar.setMaximumSize(new java.awt.Dimension(53, 27));
        guardar.setMinimumSize(new java.awt.Dimension(53, 27));
        guardar.setPreferredSize(new java.awt.Dimension(53, 27));
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        jugadorBlancoTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugadorBlancoTXTActionPerformed(evt);
            }
        });

        jugadorNegroTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugadorNegroTXTActionPerformed(evt);
            }
        });

        jugadorNegro.setText("Jugador negro: ");

        anioTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anioTXTActionPerformed(evt);
            }
        });

        anio.setText("Aňo / Identificador:");

        cargarFoto.setText("Cargar foto");
        cargarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarFotoActionPerformed(evt);
            }
        });

        direccionImagen.setMaximumSize(new java.awt.Dimension(75, 23));
        direccionImagen.setMinimumSize(new java.awt.Dimension(75, 23));
        direccionImagen.setPreferredSize(new java.awt.Dimension(75, 23));

        tablero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/board2.png"))); // NOI18N
        tablero.setVerifyInputWhenFocusTarget(false);

        cancelar1.setText("Cancelar");
        cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jugadorBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jugadorBlancoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jugadorNegro, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jugadorNegroTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(anio, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(anioTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cargarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(direccionImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tablero, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(276, 276, 276)
                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jugadorBlanco))
                    .addComponent(jugadorBlancoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jugadorNegro))
                    .addComponent(jugadorNegroTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(anio))
                    .addComponent(anioTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cargarFoto)
                    .addComponent(direccionImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tablero)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelar1)
                    .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void setBoardPicture(){
        try{
            direccionImagen.setText(fichero.getPath());
            ImageIcon icon = new ImageIcon(fichero.toString());
            Icon icono = new ImageIcon(icon.getImage().getScaledInstance(
            tablero.getWidth(), tablero.getHeight(), Image.SCALE_DEFAULT));
            tablero.setIcon(icono);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "El archivo ha sido removido o cambiado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void copyFile(File s, File t){
        try{
              FileChannel in = (new FileInputStream(s)).getChannel();
              FileChannel out = (new FileOutputStream(t)).getChannel();
              in.transferTo(0, s.length(), out);
              in.close();
              out.close();
        }
        catch(Exception e){}
    }
    
    private void jugadorBlancoTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugadorBlancoTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jugadorBlancoTXTActionPerformed

    private void jugadorNegroTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugadorNegroTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jugadorNegroTXTActionPerformed

    private void anioTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anioTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anioTXTActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        partida.getListaDeJugadas().remove(index);
        String pJugadorBlanco, pJugadorNegro, pAnio;
        pJugadorBlanco = jugadorBlancoTXT.getText();
        pJugadorNegro = jugadorNegroTXT.getText();
        pAnio = anioTXT.getText();
        JugadaTactica nuevaJugadaTactica = new JugadaTactica (pJugadorBlanco, pJugadorNegro, pAnio, fichero);
        partida.anadirJugada( (Jugada)nuevaJugadaTactica );
        application.EntrenadorDeAjedrez.setPartida(partida);
        application.EntrenadorDeAjedrez.write();
        this.dispose();
    }//GEN-LAST:event_guardarActionPerformed

    private void cargarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarFotoActionPerformed
        int resultado;
        File copyFileAux;
        SeleccionarArchivo ventana = new SeleccionarArchivo();
        Date date = new Date() ;
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH-mm-ss");
        try{
            ventana.fileChooser.setCurrentDirectory(new File (System.getProperty("user.home") + System.getProperty("file.separator")+ "Pictures"));
        }
        catch (Exception e){}
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG"
                                                                  ,"jpg","png");
        ventana.fileChooser.setFileFilter(filtro);
        resultado = ventana.fileChooser.showOpenDialog(null);
        if (JFileChooser.APPROVE_OPTION == resultado){
            if (fichero != null){
                fichero.delete();
            }
            copyFileAux = ventana.fileChooser.getSelectedFile();
            copyFile(copyFileAux, new File("src/resources/images/" + dateFormat.format(date) + ".png"));
            fichero = new File ("src/resources/images/" + dateFormat.format(date) + ".png");
        }
        setBoardPicture();
    }//GEN-LAST:event_cargarFotoActionPerformed

    private void cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anio;
    private javax.swing.JTextField anioTXT;
    private javax.swing.JToggleButton cancelar1;
    private javax.swing.JButton cargarFoto;
    private javax.swing.JLabel direccionImagen;
    private javax.swing.JToggleButton guardar;
    private javax.swing.JLabel jugadorBlanco;
    private javax.swing.JTextField jugadorBlancoTXT;
    private javax.swing.JLabel jugadorNegro;
    private javax.swing.JTextField jugadorNegroTXT;
    private javax.swing.JLabel tablero;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
