/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.nio.channels.FileChannel;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Jugada;
import model.JugadaTeorica;
import model.Partida;

/**
 *
 * @author jeffrey-lmde
 */
public class EditarJugadaTeorica extends javax.swing.JFrame {
    private File fichero;
    private int index;
    private JugadaTeorica jugada;
    private Partida partida;
    /**
     * Creates new form CrearJugadaTeorica
     */
    public EditarJugadaTeorica(int pIndex) {
        initComponents();
        partida = application.EntrenadorDeAjedrez.getPartida();
        index = pIndex;
        jugada = (JugadaTeorica) partida.getListaDeJugadas().get(index);
        fichero = jugada.getImagen();
        nombreTXT.setText(jugada.getNombre());
        anioTXT.setText(jugada.getAnio());
        setBoardPicture();
        setIconImage(new ImageIcon(getClass().getResource("../resources/icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        nombreTXT = new javax.swing.JTextField();
        cancelar = new javax.swing.JToggleButton();
        cargarFoto = new javax.swing.JButton();
        anio = new javax.swing.JLabel();
        anioTXT = new javax.swing.JTextField();
        direccionImagen = new javax.swing.JLabel();
        tablero = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entrenador de Ajedrez");
        setMinimumSize(new java.awt.Dimension(500, 655));
        setResizable(false);

        titulo.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Jugada Teorica");

        nombre.setText("Nombre: ");

        nombreTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTXTActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        cargarFoto.setText("Cargar foto");
        cargarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarFotoActionPerformed(evt);
            }
        });

        anio.setText("Aňo / Identificador:");

        anioTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anioTXTActionPerformed(evt);
            }
        });

        direccionImagen.setMaximumSize(new java.awt.Dimension(75, 23));
        direccionImagen.setMinimumSize(new java.awt.Dimension(75, 23));
        direccionImagen.setPreferredSize(new java.awt.Dimension(75, 23));

        tablero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/board2.png"))); // NOI18N

        guardar.setText("Guardar");
        guardar.setMaximumSize(new java.awt.Dimension(100, 23));
        guardar.setMinimumSize(new java.awt.Dimension(100, 23));
        guardar.setPreferredSize(new java.awt.Dimension(100, 23));
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nombreTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(anio, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(anioTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cargarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(direccionImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tablero, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(267, 267, 267)
                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(nombre))
                    .addComponent(nombreTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(anio))
                    .addComponent(anioTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cargarFoto)
                    .addComponent(direccionImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tablero)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelar)
                    .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setBoardPicture(){
        try{
            direccionImagen.setText(fichero.getPath());
            ImageIcon icon = new ImageIcon(fichero.toString());
            Icon icono = new ImageIcon(icon.getImage().getScaledInstance(
            tablero.getWidth(), tablero.getHeight(), Image.SCALE_DEFAULT));
            tablero.setIcon(icono);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "El archivo ha sido removido o cambiado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void copyFile(File s, File t){
        try{
              FileChannel in = (new FileInputStream(s)).getChannel();
              FileChannel out = (new FileOutputStream(t)).getChannel();
              in.transferTo(0, s.length(), out);
              in.close();
              out.close();
        }
        catch(Exception e){}
    }
    
    private void nombreTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTXTActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void cargarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarFotoActionPerformed
        int resultado;
        File copyFileAux;
        SeleccionarArchivo ventana = new SeleccionarArchivo();
        Date date = new Date() ;
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH-mm-ss");
        try{
            ventana.fileChooser.setCurrentDirectory(new File (System.getProperty("user.home") + System.getProperty("file.separator")+ "Pictures"));
        }
        catch (Exception e){}
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG"
                                                                  ,"jpg","png");
        ventana.fileChooser.setFileFilter(filtro);
        resultado = ventana.fileChooser.showOpenDialog(null);
        if (JFileChooser.APPROVE_OPTION == resultado){
            if (fichero != null){
                fichero.delete();
            }
            copyFileAux = ventana.fileChooser.getSelectedFile();
            copyFile(copyFileAux, new File("src/resources/images/" + dateFormat.format(date) + ".png"));
            fichero = new File ("src/resources/images/" + dateFormat.format(date) + ".png");
        }
        setBoardPicture();
    }//GEN-LAST:event_cargarFotoActionPerformed

    private void anioTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anioTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anioTXTActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        partida.getListaDeJugadas().remove(index);
        String pNombre, pAnio;
        Jugada pJugada;
        pNombre = nombreTXT.getText();
        pAnio = anioTXT.getText();
        JugadaTeorica nuevaJugadaTeorica = new JugadaTeorica (pNombre, pAnio, fichero);
        partida.anadirJugada( (Jugada)nuevaJugadaTeorica );
        application.EntrenadorDeAjedrez.setPartida(partida);
        application.EntrenadorDeAjedrez.write();
        this.dispose();
    }//GEN-LAST:event_guardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anio;
    private javax.swing.JTextField anioTXT;
    private javax.swing.JToggleButton cancelar;
    private javax.swing.JButton cargarFoto;
    private javax.swing.JLabel direccionImagen;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombreTXT;
    private javax.swing.JLabel tablero;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
