/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.ImageIcon;

/**
 *
 * @author jeffrey-lmde
 */
public class ElegirTipoDeJugada extends javax.swing.JFrame {

    /**
     * Creates new form ElegirTipoDeJugada
     */
    public ElegirTipoDeJugada() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../resources/icon.png")).getImage());
        tactica.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        tactica = new javax.swing.JRadioButton();
        teorica = new javax.swing.JRadioButton();
        cancelar = new javax.swing.JToggleButton();
        siguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entrenador de Ajedrez");
        setLocation(new java.awt.Point(720, 450));
        setResizable(false);

        titulo.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Elegir tipo de jugada");

        tactica.setText("Jugada tactica");
        tactica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tacticaActionPerformed(evt);
            }
        });

        teorica.setText("Jugada teorica");
        teorica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teoricaActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tactica, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(151, 151, 151))
                            .addComponent(teorica, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(tactica)
                .addGap(18, 18, 18)
                .addComponent(teorica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar)
                    .addComponent(siguiente))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void tacticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tacticaActionPerformed
        if (teorica.isSelected()){
            teorica.setSelected(false);
        }
        tactica.setSelected(true);
    }//GEN-LAST:event_tacticaActionPerformed

    private void teoricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teoricaActionPerformed
        if (tactica.isSelected()){
            tactica.setSelected(false);
        }
        teorica.setSelected(true);
    }//GEN-LAST:event_teoricaActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        this.dispose();
        if (tactica.isSelected()){
            CrearJugadaTactica crearJugadaTactica = new CrearJugadaTactica();
            crearJugadaTactica.setLocationRelativeTo(null);
            crearJugadaTactica.setVisible(true);
        }
        else if (teorica.isSelected()){
            CrearJugadaTeorica crearJugadaTeorica = new CrearJugadaTeorica();
            crearJugadaTeorica.setLocationRelativeTo(null);
            crearJugadaTeorica.setVisible(true);
        }
    }//GEN-LAST:event_siguienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton cancelar;
    private javax.swing.JButton siguiente;
    private javax.swing.JRadioButton tactica;
    private javax.swing.JRadioButton teorica;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
