/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jeffrey-lmde
 */
public class MenuDeJugadas extends javax.swing.JFrame {

    /**
     * Creates new form MenuDeJugadas
     */
    public MenuDeJugadas() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../resources/icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        crearJugada = new javax.swing.JToggleButton();
        editarJugada = new javax.swing.JToggleButton();
        borrarJugada = new javax.swing.JToggleButton();
        cancelar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entrenador de Ajedrez");
        setLocation(new java.awt.Point(720, 450));
        setResizable(false);

        titulo.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Menu de Jugadas");

        crearJugada.setText("Crear Jugada");
        crearJugada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearJugadaActionPerformed(evt);
            }
        });

        editarJugada.setText("Editar Jugada");
        editarJugada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarJugadaActionPerformed(evt);
            }
        });

        borrarJugada.setText("Borrar Jugada");
        borrarJugada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarJugadaActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(crearJugada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editarJugada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(borrarJugada, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 138, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(crearJugada)
                .addGap(18, 18, 18)
                .addComponent(editarJugada)
                .addGap(18, 18, 18)
                .addComponent(borrarJugada)
                .addGap(18, 18, 18)
                .addComponent(cancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrarJugadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarJugadaActionPerformed
        if(!application.EntrenadorDeAjedrez.getPartida().getListaDeJugadas().isEmpty()){
            BorrarJugada nuevoBorrarJugada = new BorrarJugada();
            nuevoBorrarJugada.setLocationRelativeTo(null);
            nuevoBorrarJugada.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "No hay jugadas a borrar", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_borrarJugadaActionPerformed

    private void editarJugadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarJugadaActionPerformed
        if(!application.EntrenadorDeAjedrez.getPartida().getListaDeJugadas().isEmpty()){
            ElegirJugada elegirJugada = new ElegirJugada();
            elegirJugada.setLocationRelativeTo(null);
            elegirJugada.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "No hay jugadas a editar", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editarJugadaActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void crearJugadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearJugadaActionPerformed
        ElegirTipoDeJugada elegirTipoDeJugada = new ElegirTipoDeJugada();
        elegirTipoDeJugada.setLocationRelativeTo(null);
        elegirTipoDeJugada.setVisible(true);
    }//GEN-LAST:event_crearJugadaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton borrarJugada;
    private javax.swing.JToggleButton cancelar;
    private javax.swing.JToggleButton crearJugada;
    private javax.swing.JToggleButton editarJugada;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
